<a href="https://colab.research.google.com/github/psudip76/Sudip-Practice/blob/main/Python_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
##Using Dictionary
data={1:"Sudip",2:"Sreekala",3:"Shreya",4: "Siddharth"}
if data.get(3)=="Shreya":
 #Calculate Marks for Shreya
 maths_mark=50
 phy_mark=40
 chem_mark=30
 total_marks=maths_mark+phy_mark+chem_mark
 print(total_marks)

In [ ]:
import numpy as np
test_arr=np.array([[1,2,3,4],
                  [5,6,7,8],
                  [9,10,11,12]])
print(np.sum(test_arr, axis=1))

[10 26 42]


In [ ]:
##Using tuple
my_tuple_1=("Sudip",49,"Engineer", "Chennai")
name, age, profession, location=my_tuple_1
print(name)
print(age)
print(profession)
print(location)

In [ ]:
##Usig tuple in dictionary
city_locations={(13.0827,13.0927):"Chennai",(13.0627,13.0499):"Hosur",(13.1422,13.1599):"Madurai"}
target_coordinate=(13.0827,13.0927)
print ("City is",city_locations.get(target_coordinate))

City is Chennai


In [ ]:
keys=("India","China", "England","France")
values=("Delhi","Beijing","London","Paris")
country_capital=dict(zip(keys,values))
print(country_capital)

In [ ]:
##program to print Chennai Summer
import numpy as np
chennai_summer=np.array(["March","April", "May","June","July"])
chennai_autumn=np.array(["August","September"])
chennai_rainy=np.array(["October,November"])
chennai_winter=np.array(["December","January","February"])
chennai_new_summer=np.concatenate((chennai_summer,chennai_autumn,chennai_rainy,chennai_winter))
print("Chennai Summer is now",chennai_new_summer)

Chennai Summer is now ['March' 'April' 'May' 'June' 'July' 'August' 'September'
 'October,November' 'December' 'January' 'February']


In [ ]:
import numpy as np  # Common alias used globally

# 1D Array (Vector)
arr_1d = np.array([1, 2, 3, 4])

# 2D Array (Matrix)
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

print(arr_2d.shape)  # Returns (2, 3) - 2 rows, 3 columns
print(arr_2d.dtype)  # Returns int64 (or int32 depending on system)

(2, 3)
int64


In [ ]:
import numpy as np
zeros=np.zeros((3,4))
print("zero array is:\n", zeros)
identity_matrix=np.eye((4))
print("identity is : \n",identity_matrix)
sequence=np.array([10,5,7,3,9,8,1,2])
print("sequence is : \n",np.sort(sequence))

zero array is:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
identity is : 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
sequence is : 
 [ 1  2  3  5  7  8  9 10]


In [ ]:
scores=np.array([50,70,60,30,45,93,67,14,98,87,77])
print("# of students who passed :",np.sum([scores>50]))
print("# of students who failed :",np.sum([scores<50]))

# of students who passed : 7
# of students who failed : 3


In [ ]:
import numpy as np
x=int(input("enter a number"))
def advanced_numpy_calculator(val):
 if(val<0):
   y=(np.exp(val)*np.cos(val))
   print("Damped Oscillation is : ",y)
 elif(0<=val<15):
   z=np.radians(val)
   y=(np.sin(2 * z)+np.cos(3 * z))
   print("Trigonometric Combination is: ",y)
 elif(15<=val<40):
   y=(np.log1p(val)*np.sqrt(val)-np.cbrt(val))
   print("Logarithmic Root Scaling: ",y)
 elif (40<=val<90):
   new_arr=np.array([[val,val/2,val/3],
                 [val/4,val/5,val/6],
                 [val/7,val/8,val/9]])
   y=np.linalg.det(new_arr)
   print("matrix determinant is: ",y)
 elif(90<=val<150):
   coeffs=[1,-3,2,-1,5]
   y=np.polyval(coeffs,val)
   print("Polynomial Evaluation: ",y)
 else:
   test_arr=np.array([[val,val/2,val/3,val/4,val/5]])
   mean_i=np.mean(test_arr)
   std_i=np.std(test_arr)
   y =mean_i+std_i
   print("Mean+standard deviation =", y)
advanced_numpy_calculator(x)

In [ ]:
import numpy as np
test_arr=np.array([[1,2,3],
                  [4,5,6]])
print (test_arr[1,2])
print(np.sum(test_arr,axis=0))
print(np.sum(test_arr,axis=1))

6
[5 7 9]
[ 6 15]
